// <auto-generated />
using System;
using EMDERSOFT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMDERSOFT.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260510013724_AgregarDetalleHerramienta")]
    partial class AgregarDetalleHerramienta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EMDERSOFT.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Electricidad"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Mecánica"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Corte"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Medición"
                        });
                });

            modelBuilder.Entity("EMDERSOFT.Models.DetalleHerramienta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Especificaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("GarantiaMeses")
                        .HasColumnType("int");

                    b.Property<int>("HerramientaId")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("decimal(8,3)");

                    b.HasKey("Id");

                    b.HasIndex("HerramientaId")
                        .IsUnique();

                    b.ToTable("DetallesHerramienta");
                });

            modelBuilder.Entity("EMDERSOFT.Models.Etiqueta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Etiquetas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "En préstamo"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "En mantenimiento"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Crítico"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Nuevo"
                        });
                });

            modelBuilder.Entity("EMDERSOFT.Models.Herramienta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Herramientas");
                });

            modelBuilder.Entity("EMDERSOFT.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("EtiquetaHerramienta", b =>
                {
                    b.Property<int>("EtiquetasId")
                        .HasColumnType("int");

                    b.Property<int>("HerramientasId")
                        .HasColumnType("int");

                    b.HasKey("EtiquetasId", "HerramientasId");

                    b.HasIndex("HerramientasId");

                    b.ToTable("HerramientaEtiqueta", (string)null);
                });

            modelBuilder.Entity("EMDERSOFT.Models.DetalleHerramienta", b =>
                {
                    b.HasOne("EMDERSOFT.Models.Herramienta", "Herramienta")
                        .WithOne("Detalle")
                        .HasForeignKey("EMDERSOFT.Models.DetalleHerramienta", "HerramientaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Herramienta");
                });

            modelBuilder.Entity("EMDERSOFT.Models.Herramienta", b =>
                {
                    b.HasOne("EMDERSOFT.Models.Categoria", "Categoria")
                        .WithMany("Herramientas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("EtiquetaHerramienta", b =>
                {
                    b.HasOne("EMDERSOFT.Models.Etiqueta", null)
                        .WithMany()
                        .HasForeignKey("EtiquetasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMDERSOFT.Models.Herramienta", null)
                        .WithMany()
                        .HasForeignKey("HerramientasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EMDERSOFT.Models.Categoria", b =>
                {
                    b.Navigation("Herramientas");
                });

            modelBuilder.Entity("EMDERSOFT.Models.Herramienta", b =>
                {
                    b.Navigation("Detalle");
                });
#pragma warning restore 612, 618
        }
    }
}
